# pull official base image
FROM node:13.12.0-alpine as build-stage

# set working directory
WORKDIR /usr/app
COPY . .
RUN npm install
RUN npm run build
RUN npm install react-scripts@3.4.1 -g

FROM node:13.12.0-alpine
COPY --from=build-stage /usr/app /usr/app
WORKDIR /usr/app
COPY package.json ./
COPY package-lock.json ./

CMD ["npm", "start"]