FROM ubuntu:20.04 

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt-get update && apt-get install -y nodejs

WORKDIR /app
COPY . .
RUN npm install
EXPOSE 5000
ENV API_URL=http://localhost:8000

CMD npm start